### ISSUE TITLE
Convert CLI tool to a dotnet tool

### ISSUE THREAD

**Issue by mariomastrodicasa** [masesgroup/KafkaBridge#26]
**Describe the bug**
The package KafkaBridgeCLI shall appears as a [dotnet tool](https://docs.microsoft.com/en-us/nuget/create-packages/set-package-type?tabs=dotnet) rather than a normal package.

**Expected behavior**
Convert the package to a dotnet tool package and give the users the ability to use the content as a console application.

**Screenshots**

![image](https://user-images.githubusercontent.com/48451703/155904335-7380c8fa-e771-4b05-afa8-bd989c2534a4.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Version: All

**Additional context**
N/A

**Comment by masesdevelopers** [comment]
To create a working dotnet tool package seems mandatory to add `PackAsTool` option within the project. Anyway testing the resulting package it does not contains all files necessary for the runtime: only the main assemblies of the referenced packages are available, the runtime libraries of JCOBridge are missing; we tested the solutions found in https://github.com/NuGet/Home/issues/4360 without success because a NuGet package hosting tools expect the files are under a folder named `any` under each runtime (`tools\net6.0\any`, `tools\net5.0\any`); at the end we concluded that a feasible option is to create a specific nuspec file, avoids the creation of package from project (i.e. disable option `GeneratePackageOnBuild`): the project is used only to create the executables.

**Comment by mariomastrodicasa** [comment]
Until now the tool needs to explicitly set the class to be used with `ClassToRun` command-line switch. A dotnet tool package can host more than one command: it is useful to create scripts (PowerShell, batch or sh) to execute the command directly:

```sh
KafkaBridgeCLI -ClassToRun ConsoleConsumer --bootstrap-server SERVER-ADDRESS:9093 --topic topic_name --from-beginning
```
becomes
```sh
ConsoleConsumer --bootstrap-server SERVER-ADDRESS:9093 --topic topic_name --from-beginning
```
